/*
PetStore API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package testsdkgo

import (
	"encoding/json"
)

// checks if the DefaultResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultResponse{}

// DefaultResponse struct for DefaultResponse
type DefaultResponse struct {
	Meta *DefaultResponseMeta `json:"_meta,omitempty"`
	// Errors specifies a list of errors that occurred, can be filled using error handlers.
	Errors map[string]interface{} `json:"errors,omitempty"`
}

// NewDefaultResponse instantiates a new DefaultResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultResponse() *DefaultResponse {
	this := DefaultResponse{}
	return &this
}

// NewDefaultResponseWithDefaults instantiates a new DefaultResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultResponseWithDefaults() *DefaultResponse {
	this := DefaultResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *DefaultResponse) GetMeta() DefaultResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret DefaultResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultResponse) GetMetaOk() (*DefaultResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *DefaultResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given DefaultResponseMeta and assigns it to the Meta field.
func (o *DefaultResponse) SetMeta(v DefaultResponseMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *DefaultResponse) GetErrors() map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultResponse) GetErrorsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return map[string]interface{}{}, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *DefaultResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string]interface{} and assigns it to the Errors field.
func (o *DefaultResponse) SetErrors(v map[string]interface{}) {
	o.Errors = v
}

func (o DefaultResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["_meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableDefaultResponse struct {
	value *DefaultResponse
	isSet bool
}

func (v NullableDefaultResponse) Get() *DefaultResponse {
	return v.value
}

func (v *NullableDefaultResponse) Set(val *DefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultResponse(val *DefaultResponse) *NullableDefaultResponse {
	return &NullableDefaultResponse{value: val, isSet: true}
}

func (v NullableDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


