// Code generated by P30599-IPC-Generator/ipcgen/internal/built-in-plugins/client; DO NOT EDIT.
package testsdkgo

// Client implementation for calling operations on SDKClient
type Client struct {
	// Configuration to construct requests for operations
	Configuration *Configuration
	// DefaultAPI is the implementation of operations grouped on the 'Default' tag
	DefaultAPI *DefaultService
	// PetsAPI is the implementation of operations grouped on the 'pets' tag
	PetsAPI *PetsService
	// StoreAPI is the implementation of operations grouped on the 'store' tag
	StoreAPI *StoreService
}

// FromConfiguration returns a *Client with all services instantiated.
func FromConfiguration(cfg *Configuration) *Client {
	return &Client{
		Configuration: cfg,
		DefaultAPI: &DefaultService{
			Client:        cfg.Client,
			Configuration: cfg,
		},
		PetsAPI: &PetsService{
			Client:        cfg.Client,
			Configuration: cfg,
		},
		StoreAPI: &StoreService{
			Client:        cfg.Client,
			Configuration: cfg,
		},
	}
}

// NewClient from option[Configuration] to create a new *Client for 'SDKClient'
func NewClient(host string, options ...option[Configuration]) (*Client, error) {
	cfg, err := NewConfiguration(host, options...)
	if err != nil {
		return nil, err
	}

	return FromConfiguration(cfg), nil
}
